apiVersion: v1
kind: Service
metadata:
  name: {{ include "engine-health-platform.componentName" (list .Release.Name "api") }}
  labels:
    app: {{ include "engine-health-platform.componentName" (list .Release.Name "api") }}
    component: api
spec:
  type: ClusterIP
  selector:
    app: {{ include "engine-health-platform.componentName" (list .Release.Name "api") }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
