apiVersion: v1
kind: Service
metadata:
  name: {{ include "engine-health-platform.componentName" (list .Release.Name "web") }}
  labels:
    app: {{ include "engine-health-platform.componentName" (list .Release.Name "web") }}
    component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app: {{ include "engine-health-platform.componentName" (list .Release.Name "web") }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      {{- if eq .Values.web.service.type "NodePort" }}
      nodePort: {{ .Values.web.service.nodePort }}
      {{- end }}
